### ISSUE TITLE
The anticipation is killing me

### ISSUE THREAD

**Issue by NickDarvey** [Reactive-Extensions/Reactor#1]
Dear @bartdesmet, will you share an update with us?

**Comment by bartdesmet** [comment]
Started to plant some CI seeds just now. We'll go piecemeal in a bottom-up fashion from here. You can expect to see a variety of utilities (basically .NET BCL extensions and other goodies) to show up first.

**Comment by NickDarvey** [comment]
I actually jumped out of my chair in excitement when I saw the notification for this comment.

That's a great approach, I look forward to seeing your creation!
