### ISSUE TITLE
Seeking Roadmap

### ISSUE THREAD

**Issue by AliBazzi** [Reactive-Extensions/Reactor#6]
Hi,

I coincidently passed by this repo, which personally I was looking for it months ago, I tried to email @bartdesmet and tried to ask on Service fabric user voice, I was wondering about the state of the project, specifically what Bart mentioned in this talk: https://www.infoq.com/presentations/cloud-rx
Can I consider this repo is the foundation for what is mentioned in Bart's talk? and if it's, any roadmap for the project? is it open for contribution?

So thrilled to see this project live and used outside Microsoft.

Thank you

**Comment by AviAvni** [comment]
@AliBazzi  look https://github.com/Reactive-Extensions/Reactor/issues/1

**Comment by AliBazzi** [comment]
Thanks !
